### ISSUE TITLE
RoundRobin::In

### ISSUE THREAD

**Issue by sombr** [berekuk/Stream-More#1]
Haven't found how to write a comment to file, but - I've a question:
I'm now looking at RoundRobin::In read_chunk sub and I can't see `while` loop terminator on empty line.
Is it true, that if you have 2 lines written before your client position:
`
line 1\n
line 2\n
\n
...
`
and you try to read_chunk(3), you'll get `[ ..., ..., "\n" ]` - with an empty line at the end?
How can you avoid this?

**Comment by berekuk** [comment]
How did this empty line got there?
If somebody wrote it to the storage, then I'd argue you should get it on reading.
If it's a part of pre-fill from storage initialization, then you shouldn't get it on `read_chunk` because it'd mean crossing the writing position.

Maybe I'm missing something here, can you provide the test case reproducing the problem?

**Comment by sombr** [comment]
yeap, my bad, you were right about crossing "write" position, it is all ok now. Just out of curiosity I've written almost compatible RR in Java :)
